# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 21:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ION', '0003_auto_20170528_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gearpost',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
