# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-13 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ION', '0004_auto_20170512_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='gearpost',
            name='photo',
            field=models.ImageField(default='/static/images/media/imgnotfound.png', upload_to='gearimages'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='text',
            field=models.TextField(max_length=1000),
        ),
    ]
