# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ION', '0005_auto_20170513_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='text',
            field=models.TextField(max_length=2500),
        ),
        migrations.AlterField(
            model_name='gearpost',
            name='photo',
            field=models.ImageField(upload_to='gearimages/'),
        ),
    ]
