# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 01:57
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ION', '0006_auto_20170523_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gearpost',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
