# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 06:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ION', '0008_auto_20170524_1900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gearpost',
            old_name='post_id',
            new_name='id',
        ),
    ]
