# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ION', '0010_auto_20170524_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='gearpost',
            name='price',
            field=models.FloatField(default=None, max_length=20),
        ),
    ]
