# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ION', '0012_auto_20170525_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gearpost',
            name='price',
            field=models.FloatField(max_length=20),
        ),
    ]
