# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ION', '0014_auto_20170525_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gearpost',
            name='price',
            field=models.IntegerField(),
        ),
    ]
