# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 21:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ION', '0015_auto_20170525_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gearpost',
            name='price',
        ),
    ]
