# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ION', '0016_remove_gearpost_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='gearpost',
            name='price',
            field=models.IntegerField(default=20),
        ),
    ]
