# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 06:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ION', '0017_gearpost_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='IOPimages/')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='gearpost',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gearpost',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
