# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 06:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ION', '0019_auto_20170525_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='photopost',
            name='author',
            field=models.ForeignKey(default='N/A', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
