# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 06:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ION', '0020_photopost_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photopost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
