# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 06:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ION', '0021_auto_20170525_2331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photopost',
            name='author',
        ),
    ]
