# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ION', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gearpost',
            name='photo',
            field=models.ImageField(default='/ION/static/images/imgnotfound.png', upload_to='gearimages/'),
        ),
    ]
