# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 19:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ION', '0002_auto_20170528_1219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gearpost',
            old_name='author',
            new_name='user',
        ),
    ]
