# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 08:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ION', '0006_auto_20170528_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='published_date',
        ),
    ]
