# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 21:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ION', '0007_remove_blogpost_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gearpost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
